name: loan_app
description: A simplified loan information and request app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  pinput: ^4.0.0 # Excellent for OTP/PIN UI
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Networking
  http: ^1.1.0

  # UI/UX
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0

  # Form handling
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0

  # Email & Backend
  url_launcher: ^6.2.1
  mailer: ^6.0.1

  # State Management
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2

  # Maps
  maps_launcher: ^3.0.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700

  